<!-- subheader -->
<section id="subheader" data-speed="8" data-type="background" style="background-position: 50% -25px; background: url('<?php echo $this->basePath('public/frontend/images/subheader-5.jpg');?>')">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
<h1 class="visible-xs"><?php echo $this->escapeHtml($postCategory['post_category_name']);?></h1>
                <?php echo $crum;?>
            </div>
        </div>
    </div>
</section>
<!-- subheader close -->




<!-- content begin -->
<div id="content" class="no-top no-bottom">
    <section id="section-about-us-2" class="side-bg no-padding">
      
        <div class="container">
            <div class="row">
                <div class="inner-padding">
                    <div class="col-md-8 wow fadeInRight" data-wow-delay=".5s">
                        <h2 style="margin-top: 0"><?php echo $this->escapeHtml($post['post_title']);?></h2>
						
						<div id="fb-root"></div>

                        <div class="fb-like" data-href="<?php echo $this->url('home-news-detail', array('name' => $this->function()->formatTitle($post['post_title']), 'id' => $post['post_id']));?>" data-layout="standard" data-action="like" data-size="small" data-show-faces="false" style="margin-bottom: 20px;"></div>


                        <?php echo $post['post_body'];?>
                    </div>
                    <?php if (count($postOther) > 0) {?>
                    <div id="sidebar" class="col-md-4">
                        <div class="widget widget-post">
                            <h4>Bài viết liên quan</h4>
                            <div class="small-border"></div>
                            <ul>
                                <?php foreach($postOther as $v) {?>
                                <li><a href="<?php echo $this->url('home-news-detail', array('name' => $this->function()->formatTitle($v['post_title']), 'id' => $v['post_id']));?>"><?php echo $this->escapeHtml($v['post_title']);?></a></li>
                               <?php }?>

                            </ul>
                        </div>
                    </div>
                    <?php }?>

                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </section>
</div>

