<?php
echo $this->formViewElement()->text('Nhóm thuộc tính', $this->escapeHtml($data['groupProperty']['group_property_name']));
echo $this->formViewElement()->text('Trạng thái', $data['status'][$data['groupProperty']['group_property_status']]);
?>

<div class="item form-group">
    <div class="col-md-12 col-sm-6 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <div class="" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Thuộc tính</a>
                        </li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                            <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
                                <thead>
                                <tr>
                                    <th><input type="checkbox" class="checkbox-all-property" /></th>
                                    <th>Thuộc tính</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($data['properties'] as $rp) : ?>
                                    <tr>
                                        <td width="100">
                                            <input class="checkbox-item-property" type="checkbox" name="property[<?php echo $rp['property_id']; ?>]"  <?php echo (array_key_exists($rp['property_id'], $data['groupPropertyDetail'])) ? 'checked="checked"' : '';?> value="1" />
                                        </td>
                                        <td><?php echo $this->escapeHtml($rp['property_name']); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

<script>
    $(function () {


        //Check all property
        $(".checkbox-all-property").change(function () {
            var chec = false;
            if ($(this).is(":checked"))
            {
                chec = true;
            }
            $(".checkbox-item-property").prop('checked', chec);
        });
    });
</script>

