<!-- subheader -->
<section id="subheader" data-speed="8" data-type="background" style="background-position: 50% -25px; background: url('<?php echo $this->basePath('public/frontend/images/subheader-5.jpg');?>')">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
<!--                <h1>--><?php //echo $this->escapeHtml($page['post_title']);?><!--</h1>-->
                <?php echo $crum;?>
            </div>
        </div>
    </div>
</section>
<!-- subheader close -->


<!-- content begin -->
<div id="content" class="no-top no-bottom">
    <section id="section-about-us-2" class="side-bg no-padding">
        <div class="image-container col-md-5 pull-left" data-delay="0"></div>

        <div class="container">
            <div class="row">
                <div class="inner-padding">
                    <div class="col-md-12 wow fadeInRight" data-wow-delay=".5s">
                        <h2><?php echo $this->escapeHtml($page['post_title']);?></h2>
                        <?php echo $page['post_body'];?>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </section>
</div>

