<!DOCTYPE html>
<!-- saved from url=(0079)http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title><?php echo $websiteGeneral['website_general_title'];?>"</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<?php echo $websiteGeneral['website_general_description'];?>">
    <meta name="keywords" content="<?php echo $websiteGeneral['website_general_keyword'];?>">


    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('pictures/websites/' . $websiteGeneral['website_general_favicon'])))
        ->prependStylesheet($this->basePath('frontend/css/font-style-2.css'))
        ->prependStylesheet($this->basePath('frontend/css/rev-settings.css'))
        ->prependStylesheet($this->basePath('frontend/css/settings.css'))
        ->prependStylesheet($this->basePath('frontend/css/style(2).css'))
        ->prependStylesheet($this->basePath('frontend/css/style(1).css'))
        ->prependStylesheet($this->basePath('frontend/css/font-awesome.css'))
        ->prependStylesheet($this->basePath('frontend/css/color.css'))
        ->prependStylesheet($this->basePath('frontend/css/bg.css'))
        ->prependStylesheet($this->basePath('frontend/css/demo.css'))
        ->prependStylesheet($this->basePath('frontend/css/style.css'))
        ->prependStylesheet($this->basePath('frontend/css/magnific-popup.css'))
        ->prependStylesheet($this->basePath('frontend/css/owl.transitions.css'))
        ->prependStylesheet($this->basePath('frontend/css/owl.theme.css'))
        ->prependStylesheet($this->basePath('frontend/css/owl.carousel.css'))
        ->prependStylesheet($this->basePath('frontend/css/plugin.css'))
        ->prependStylesheet($this->basePath('frontend/css/animate.css'))
        ->prependStylesheet($this->basePath('frontend/css/jpreloader.css'))
        ->prependStylesheet($this->basePath('frontend/css/bootstrap.css'))
    ?>


    <?php echo $this->inlineScript()
        ->prependFile($this->basePath('frontend/js/jquery.themepunch.revolution.min.js'))
        ->prependFile($this->basePath('frontend/js/jquery.themepunch.plugins.min.js'))
        ->prependFile($this->basePath('frontend/js/demo.js'))
        ->prependFile($this->basePath('frontend/js/designesia.js'))
        ->prependFile($this->basePath('frontend/js/enquire.min.js'))
        ->prependFile($this->basePath('frontend/js/jquery.magnific-popup.min.js'))
        ->prependFile($this->basePath('frontend/js/wow.min.js'))
        ->prependFile($this->basePath('frontend/js/validation.js'))
        ->prependFile($this->basePath('frontend/js/video.resize.js'))
        ->prependFile($this->basePath('frontend/js/classie.js'))
        ->prependFile($this->basePath('frontend/js/jquery.countTo.js'))
        ->prependFile($this->basePath('frontend/js/owl.carousel.js'))
        ->prependFile($this->basePath('frontend/js/jquery.scrollto.js'))
        ->prependFile($this->basePath('frontend/js/jquery.flexslider-min.js'))
        ->prependFile($this->basePath('frontend/js/easing.js'))
        ->prependFile($this->basePath('frontend/js/jquery.isotope.min.js'))
        ->prependFile($this->basePath('frontend/js/bootstrap.min.js'))
        ->prependFile($this->basePath('frontend/js/jpreLoader.js'))
        ->prependFile($this->basePath('frontend/js/jquery.min.js'))
    ; ?>

</head>

<body id="homepage" style="display: block;">

<div id="wrapper">

    <!-- header begin -->
    <header class="header-light">
        <div class="info">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col">Working Hours Monday - Friday <span class="id-color"><strong>08:00-16:00</strong></span></div>
                        <div class="col">Toll Free <span class="id-color"><strong>1800.899.900</strong></span></div>
                        <!-- social icons -->
                        <div class="col social">
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-facebook"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-twitter"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-rss"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-google-plus"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-envelope-o"></i></a>
                        </div>
                        <!-- social icons close -->
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- logo begin -->
                    <div id="logo">
                        <a href="<?php echo $this->url('home');?>">
                            <img class="logo" src="<?php echo $this->basePath('frontend/images/');?>logo_lifedeco.png" alt="">
                        </a>
                    </div>
                    <!-- logo close -->

                    <!-- small button begin -->
                    <span id="menu-btn"></span>
                    <!-- small button close -->

                    <!-- mainmenu begin -->
                    <nav>
                        <ul id="mainmenu">

                            <?php foreach ($navigations as $v) : ?>
                                <?php if ($v['navigation_parent'] == 0) : ?>
                                    <?php $sub = false;
                                    $s = ''; ?>
                                    <?php
                                    foreach ($navigations as $vv) {
                                        if ($vv['navigation_parent'] == $v['navigation_id']) {
                                            $sub = true;
                                            $s .= '<li><a href="' . $vv['navigation_url_name'] . '">' . $this->escapeHtml($vv['navigation_name']) . '</a></li>';
                                        }
                                    }
                                    ?>
                                    <?php if ($sub == true) {
                                        echo '<li><a href="' . $v['navigation_url_name'] . '">' . $v['navigation_name'] . '</a><span></span><ul>' . $s . '</ul></li>';
                                    } else {
                                        echo '<li><a href="' . $v['navigation_url_name'] . '">' . $this->escapeHtml($v['navigation_name']) . '</a></li>';
                                    } ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </nav>

                </div>
                <!-- mainmenu close -->

            </div>
        </div>
    </header>
    <!-- header close -->

    <!-- content begin -->


        <?php echo $this->content;?>
        <!-- footer begin -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <img src="<?php echo $this->basePath('frontend/images/');?>logo_lifedeco.png" class="logo-small" alt=""><br>
                        Công ty chúng tôi được thành lập bởi nhóm kiến trúc sư trẻ năng động và đầy nhiệt huyết, mang trong mình khát vọng đam mê sáng tạo, những người có nhiều năm kinh nghiệm, mong muốn làm đẹp không gian sống cho mọi người. Chúng tôi luôn mong muốn mang đến sự hài lòng nhất đến với Khách Hàng.
                    </div>

                    <div class="col-md-4">
                        <div class="widget widget_recent_post">
                            <h3>Bài viết mới</h3>
                            <ul>
                                <?php foreach($posts as $v) {?>
                                <li><a href="<?php echo $this->url('home-news-detail', array('name' => $this->function()->formatTitle($v['post_title']), 'id' => $v['post_id']));?>"><?php echo $this->escapeHtml($v['post_title']);?></a></li>
                                <?php }?>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h3>Contact Us</h3>
                        <div class="widget widget-address">
                            <address>
                                <span>562 Nguyễn Chí Thanh, Phường 07, Quận 11, Tp. HCM</span>
                                <span><strong>Phone:</strong>(+84) 22 534 543</span>
                                <span><strong>Fax:</strong>(+84) 22 534 543</span>
                                <span><strong>Email:</strong><a href="mailto:info@lifedeco.vn">info@lifedeco.vn</a></span>
                                <span><strong>Web:</strong><a href="http://lifedeco.vn">lifedeco.vn</a></span>
                            </address>
                        </div>
                    </div>
                </div>
            </div>

            <div class="subfooter">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            © Copyright 2017
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="social-icons">
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-facebook fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-twitter fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-rss fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-google-plus fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-skype fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-dribbble fa-lg"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('home');?>#" id="back-to-top"></a>
        </footer>
        <!-- footer close -->

</div>

<?php if ($controller != 'index') {?>
<script>
    $(function(){
        $('header').attr('class', 'header-bg');
        $('body').attr('class', 'de_light');
    });
</script>
<?php }?>


</body></html>