<!DOCTYPE html>
<!-- saved from url=(0079)http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>LifeDeco</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('frontend/css/font-style-2.css'))
        ->prependStylesheet($this->basePath('frontend/css/rev-settings.css'))
        ->prependStylesheet($this->basePath('frontend/css/settings.css'))
        ->prependStylesheet($this->basePath('frontend/css/style(2).css'))
        ->prependStylesheet($this->basePath('frontend/css/style(1).css'))
        ->prependStylesheet($this->basePath('frontend/css/font-awesome.css'))
        ->prependStylesheet($this->basePath('frontend/css/color.css'))
        ->prependStylesheet($this->basePath('frontend/css/bg.css'))
        ->prependStylesheet($this->basePath('frontend/css/demo.css'))
        ->prependStylesheet($this->basePath('frontend/css/style.css'))
        ->prependStylesheet($this->basePath('frontend/css/magnific-popup.css'))
        ->prependStylesheet($this->basePath('frontend/css/owl.transitions.css'))
        ->prependStylesheet($this->basePath('frontend/css/owl.theme.css'))
        ->prependStylesheet($this->basePath('frontend/css/owl.carousel.css'))
        ->prependStylesheet($this->basePath('frontend/css/plugin.css'))
        ->prependStylesheet($this->basePath('frontend/css/animate.css'))
        ->prependStylesheet($this->basePath('frontend/css/jpreloader.css'))
        ->prependStylesheet($this->basePath('frontend/css/bootstrap.css'))
    ?>

</head>

<body id="homepage" class="de_light" style="display: block;">

<div id="wrapper">

    <!-- header begin -->
    <header class="header-light">
        <div class="info">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col">Working Hours Monday - Friday <span class="id-color"><strong>08:00-16:00</strong></span></div>
                        <div class="col">Toll Free <span class="id-color"><strong>1800.899.900</strong></span></div>
                        <!-- social icons -->
                        <div class="col social">
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-facebook"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-twitter"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-rss"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-google-plus"></i></a>
                            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-envelope-o"></i></a>
                        </div>
                        <!-- social icons close -->
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- logo begin -->
                    <div id="logo">
                        <a href="http://www.themenesia.com/themeforest/archi-light/index.html">
                            <img class="logo" src="<?php echo $this->basePath('frontend/images/');?>logo-3.png" alt="">
                        </a>
                    </div>
                    <!-- logo close -->

                    <!-- small button begin -->
                    <span id="menu-btn"></span>
                    <!-- small button close -->

                    <!-- mainmenu begin -->
                    <nav>
                        <ul id="mainmenu">
                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index.html">Home</a><span></span>
                                <ul>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-fresh.html">New: Fresh</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-big-3-cols.html">New: Masonry</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">Medium Grid</a><span></span>
                                                <ul>
                                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html">3 Cols</a></li>
                                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-4-cols.html">4 Cols</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">Big Grid</a><span></span>
                                                <ul>
                                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-big-3-cols.html">3 Cols</a></li>
                                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-big-4-cols.html">4 Cols</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">No Grid</a><span></span>
                                                <ul>
                                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-no-grid-3-cols.html">3 Cols</a></li>
                                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-no-grid-4-cols.html">4 Cols</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-profession.html">New: Profession</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-new.html">Modern 2</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-header-bottom.html">Menu Bottom</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-minimal.html">Minimal</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-slider-2.html">Modern</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-sidebar.html">Menu Side</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-sidebar.html">Sidebar Parallax</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-sidebar-slider.html">Sidebar Slider</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-landing-page.html">Landing Page</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-landing-page.html">Parallax</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-landing-page-video.html">Video</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index-onepage.html">One Page Style</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/index.html">Original</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index.html">Slider</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-parallax.html">Parallax</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/index-video.html">Video</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects.html">Projects</a><span></span>
                                <ul>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/projects.html">Wide Style</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-2-cols.html">2 Cols Wide</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-3-cols.html">3 Cols Wide</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects.html">4 Cols Wide</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-contained-3-cols.html">Contained Style</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-contained-2-cols.html">2 Cols Contained</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-contained-3-cols.html">3 Cols Contained</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-contained-4-cols.html">4 Cols Contained</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-carousel-3-cols.html">Carousel Style</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-carousel-2-cols.html">2 Cols Carousel</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-carousel-3-cols.html">3 Cols Carousel</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-carousel-4-cols.html">4 Cols Carousel</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-inverted-3-cols.html">Inverted Style</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-inverted-2-cols.html">2 Cols Inverted</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-inverted-3-cols.html">3 Cols Inverted</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-inverted-4-cols.html">4 Cols Inverted</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/projects-contained-3-cols.html">Simple Gallery</a><span></span>
                                        <ul>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/gallery-4-cols.html">4 Cols</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/gallery-3-cols.html">3 Cols</a></li>
                                            <li><a href="http://www.themenesia.com/themeforest/archi-light/gallery-2-cols.html">2 Cols</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="http://www.themenesia.com/themeforest/archi-light/services.html">Services</a><span></span>
                                <ul>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/service-1.html">Residential Design</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/service-2.html">Hospitaly Design</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/service-3.html">Office Design</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/service-4.html">Commercial Design</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/services.html">All Services</a></li>
                                    <li><a href="http://www.themenesia.com/themeforest/archi-light/services-style-2.html">New All Services</a></li>
                                </ul>
                            </li>
                            <li><a href="http://www.themenesia.com/themeforest/archi-light/about.html">About Us</a></li>
                            <li><a href="http://www.themenesia.com/themeforest/archi-light/blog.html">Blog</a></li>
                            <li><a href="http://www.themenesia.com/themeforest/archi-light/shop.html">Shop</a></li>
                            <li><a href="http://www.themenesia.com/themeforest/archi-light/contact.html">Contact</a></li>
                        </ul>
                    </nav>

                </div>
                <!-- mainmenu close -->

            </div>
        </div>
    </header>
    <!-- header close -->

    <!-- content begin -->
    <div id="content" class="no-bottom no-top">

        <section class="no-top no-bottom mt70 mt-sm-0">
            <div class="grid" data-col="3" data-gridspace="10" data-ratio="466/700" style="padding-left: 10px; position: relative; height: 1692.7px;">
                <div class="grid-sizer"></div>
                <div class="grid-item residential" style="width: 620.667px; height: 413.187px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 10px; top: 0px;">
                    <!-- gallery item -->
                    <div class="item">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="http://www.themenesia.com/themeforest/archi-light/project-details-1.html">
                                    <span class="overlay" style="opacity: 0;">
                                        <span class="pf_title" style="margin-top: 196.593px;">
                                            <span class="project-name">Eco Green Interior</span>
                                        </span>
                                    </span>
                            </a>
                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (1).jpg" alt="">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>
                <div class="grid-item large-width hospitaly" style="width: 1251.33px; height: 413.187px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 640px; top: 0px;">
                    <!-- gallery item -->
                    <div class="item">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="http://www.themenesia.com/themeforest/archi-light/project-details-2.html">
                                    <span class="overlay" style="opacity: 0; width: 1251px; height: 537px;">
                                        <span class="pf_title" style="margin-top: 196.593px;">
                                            <span class="project-name">Modern Elegance Suite</span>
                                        </span>
                                    </span>
                            </a>

                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (2).jpg" alt="" style="display: inline-block; width: 102.425%; height: 166.097%; margin-left: -15.1999px; margin-top: -6.52466px; overflow: hidden;">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>
                <div class="grid-item large-height hospitaly" style="width: 620.667px; height: 836.373px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 10px; top: 423px;">
                    <!-- gallery item -->
                    <div class="item">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="http://www.themenesia.com/themeforest/archi-light/project-details-3.html">
                                    <span class="overlay" style="opacity: 0;">
                                        <span class="pf_title" style="margin-top: 393.187px;">
                                            <span class="project-name">Apartment Renovation</span>
                                        </span>
                                    </span>
                            </a>

                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (3).jpg" alt="">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>
                <div class="grid-item residential" style="width: 620.667px; height: 413.187px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 640px; top: 423px;">
                    <!-- gallery item -->
                    <div class="item">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="http://www.themenesia.com/themeforest/archi-light/project-details-youtube.html">
                                    <span class="overlay" style="opacity: 0; width: 621px; height: 413px;">
                                        <span class="pf_title" style="margin-top: 196.593px;">
                                            <span class="project-name">Youtube Video</span>
                                        </span>
                                    </span>
                            </a>
                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (4).jpg" alt="" style="display: inline-block; width: 100%; height: 100%; margin-left: 0px; margin-top: 0px;">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>
                <div class="grid-item large-height office" style="width: 620.667px; height: 836.373px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 1271px; top: 423px;">
                    <!-- gallery item -->
                    <div class="item">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="http://www.themenesia.com/themeforest/archi-light/project-details-vimeo.html">
                                    <span class="overlay" style="opacity: 0; width: 621px; height: 964px;">
                                        <span class="pf_title" style="margin-top: 393.187px;">
                                            <span class="project-name">Vimeo Video</span>
                                        </span>
                                    </span>
                            </a>
                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (5).jpg" alt="" style="display: inline-block; width: 100.258%; height: 237.799%; margin-left: -0.735687px; margin-top: -1.14203px; overflow: hidden;">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>
                <div class="grid-item commercial" style="width: 620.667px; height: 413.187px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 640px; top: 846px;">
                    <!-- gallery item -->
                    <div class="item">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="http://www.themenesia.com/themeforest/archi-light/project-details.html">
                                    <span class="overlay" style="opacity: 0;">
                                        <span class="pf_title" style="margin-top: 196.593px;">
                                            <span class="project-name">Restaurant In Texas</span>
                                        </span>
                                    </span>
                            </a>
                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (6).jpg" alt="">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>

                <div class="grid-item large-width office" style="width: 1251.33px; height: 413.187px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 10px; top: 1269px;">
                    <!-- gallery item -->
                    <div class="item office">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top" href="http://www.themenesia.com/themeforest/archi-light/project-details.html">
                                    <span class="overlay" style="opacity: 0;">
                                        <span class="pf_title" style="margin-top: 196.593px;">
                                            <span class="project-name">Office On Space</span>
                                        </span>
                                    </span>
                            </a>

                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (8).jpg" alt="">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>

                <div class="grid-item residential" style="width: 620.667px; height: 413.187px; margin-right: 10px; margin-bottom: 10px; position: absolute; left: 1271px; top: 1269px;">
                    <!-- gallery item -->
                    <div class="item residential">
                        <div class="picframe">
                            <a class="simple-ajax-popup-align-top">
                                    <span class="overlay" style="opacity: 0;">
                                        <span class="pf_title" style="margin-top: 196.593px;">
                                            <span class="project-name">Summer House</span>
                                        </span>
                                    </span>
                            </a>

                            <img src="<?php echo $this->basePath('frontend/images/');?>pf (7).jpg" alt="">
                        </div>
                    </div>
                    <!-- close gallery item -->
                </div>


            </div>
        </section>


        <section id="section-why-choose-us-2">

            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3 text-center wow fadeInUp" style="visibility: hidden; animation-name: none;">
                        <h1>Why Choose Us</h1>
                        <div class="separator"><span><i class="fa fa-circle"></i></span></div>
                        <div class="spacer-single"></div>
                    </div>

                    <div class="col-md-6 wow fadeInUp" data-wow-delay="0s" style="visibility: hidden; animation-delay: 0s; animation-name: none;">
                        <div class="box-icon border">
                            <span class="icon wow fadeIn" data-wow-delay=".5s" style="visibility: hidden; animation-delay: 0.5s; animation-name: none;"><i class="id-color icon-paintbrush"></i></span>
                            <div class="text">
                                <h3>Interior Expertise</h3>
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi.</p>
                                <a class="strong id-color" href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">Learn More</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 mb30 wow fadeInUp" data-wow-delay=".25s" style="visibility: hidden; animation-delay: 0.25s; animation-name: none;">
                        <div class="box-icon border">
                            <span class="icon wow fadeIn" data-wow-delay=".75s" style="visibility: hidden; animation-delay: 0.75s; animation-name: none;"><i class="id-color icon-trophy"></i></span>
                            <div class="text">
                                <h3>Awards Winning</h3>
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi.</p>
                                <a class="strong id-color" href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">Learn More</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 mb30 wow fadeInUp" data-wow-delay=".75s" style="visibility: hidden; animation-delay: 0.75s; animation-name: none;">
                        <div class="box-icon border">
                            <span class="icon wow fadeIn" data-wow-delay="1.25s" style="visibility: hidden; animation-delay: 1.25s; animation-name: none;"><i class="id-color icon-chat"></i></span>
                            <div class="text">
                                <h3>Free Consultation</h3>
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi.</p>
                                <a class="strong id-color" href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">Learn More</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 wow fadeInUp" data-wow-delay="1s" style="visibility: hidden; animation-delay: 1s; animation-name: none;">
                        <div class="box-icon border">
                            <span class="icon wow fadeIn" data-wow-delay="1.75s" style="visibility: hidden; animation-delay: 1.75s; animation-name: none;"><i class="id-color icon-recycle"></i></span>
                            <div class="text">
                                <h3>Guaranteed Works</h3>
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi.</p>
                                <a class="strong id-color" href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">Learn More</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>

        <!-- section begin -->
        <section id="section-services" class="text-light" data-bgcolor="#1b1e20" style="background-color: rgb(27, 30, 32);">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3 text-center wow fadeInUp" style="visibility: hidden; animation-name: none;">
                        <h1>What We Do</h1>
                        <div class="separator"><span><i class="fa fa-circle"></i></span></div>
                        <div class="spacer-single"></div>
                    </div>

                    <div class="col-md-4 text-middle text-light wow fadeInRight" data-wow-delay="0" style="visibility: hidden; animation-name: none;">
                        <div class="shadow-soft" data-bgimage="url(index_files/p1_b.jpg)" style="background-image: url(&quot;index_files/p1_b.jpg&quot;);">
                            <div class="padding40 overlay60">
                                <h3>Residential Design</h3>
                                <p>Our commitment to quality and services ensure our clients happy. With years of experiences and continuing research, our team is ready to serve your interior design needs. We're happy to make you feel more comfortable on your home.</p>
                                <a href="http://www.themenesia.com/themeforest/archi-light/service-1.html" class="btn-line btn-fullwidth">Read More</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 text-middle text-light wow fadeInRight" data-wow-delay=".1s" style="visibility: hidden; animation-delay: 0.1s; animation-name: none;">
                        <div class="shadow-soft" data-bgimage="url(index_files/p3_b.jpg)" style="background-image: url(&quot;index_files/p3_b.jpg&quot;);">
                            <div class="padding40 overlay60">
                                <h3>Office Design</h3>
                                <p>Our commitment to quality and services ensure our clients happy. With years of experiences and continuing research, our team is ready to serve your interior design needs. We're happy to make you feel more comfortable on your home.</p>
                                <a href="http://www.themenesia.com/themeforest/archi-light/service-1.html" class="btn-line btn-fullwidth">Read More</a>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 text-middle text-light wow fadeInRight" data-wow-delay=".3s" style="visibility: hidden; animation-delay: 0.3s; animation-name: none;">
                        <div class="shadow-soft" data-bgimage="url(index_files/p4_a.jpg)" style="background-image: url(&quot;index_files/p4_a.jpg&quot;);">
                            <div class="padding40 overlay60">
                                <h3>Commercial Design</h3>
                                <p>Our commitment to quality and services ensure our clients happy. With years of experiences and continuing research, our team is ready to serve your interior design needs. We're happy to make you feel more comfortable on your home.</p>
                                <a href="http://www.themenesia.com/themeforest/archi-light/service-1.html" class="btn-line btn-fullwidth">Read More</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        <!-- section close -->

        <!-- section begin -->
        <section id="view-all-projects" class="call-to-action bg-color text-center text-dark padding20" data-speed="5" data-type="background" aria-label="cta">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h2>Do you ready to renovate your home? </h2>
                    </div>

                    <div class="col-md-4">
                        <a href="http://www.themenesia.com/themeforest/archi-light/contact.html" class="btn btn-line-black btn-big mt20 wow fadeInUp" style="visibility: hidden; animation-name: none;">Get Quotation</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- logo carousel section close -->

        <!-- section begin -->
        <section id="section-testimonial" class="text-light">
            <div class="container">
                <div class="col-md-6 col-md-offset-3 text-center wow fadeInUp">
                    <h1>What They Says</h1>
                    <div class="separator"><span><i class="fa fa-circle"></i></span></div>
                    <div class="spacer-single"></div>
                </div>
                <div id="testimonial-carousel" class="de_carousel  wow fadeInUp" data-wow-delay=".3s">

                    <div class="col-md-6 item">
                        <div class="de_testi">
                            <blockquote>
                                <p>I'm always impressed with the services. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
                                <div class="de_testi_by">
                                    John, Customer
                                </div>
                            </blockquote>

                        </div>
                    </div>

                    <div class="col-md-6 item">
                        <div class="de_testi">
                            <blockquote>
                                <p>I have very much enjoyed with your services. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
                                <div class="de_testi_by">
                                    Michael, Customer
                                </div>
                            </blockquote>
                        </div>
                    </div>

                    <div class="col-md-6 item">
                        <div class="de_testi">
                            <blockquote>
                                <p>I totally recommend your services. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
                                <div class="de_testi_by">
                                    Patrick, Customer
                                </div>
                            </blockquote>
                        </div>
                    </div>

                    <div class="col-md-6 item">
                        <div class="de_testi">
                            <blockquote>
                                <p>I have very much enjoyed with your services. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.</p>
                                <div class="de_testi_by">
                                    James, Customer
                                </div>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- section close -->
        <!-- section close -->

        <!-- footer begin -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <img src="<?php echo $this->basePath('frontend/images/');?>logo.png" class="logo-small" alt=""><br>
                        We are team based on Brookylin. Our expertise on Interior Design. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                    </div>

                    <div class="col-md-4">
                        <div class="widget widget_recent_post">
                            <h3>Latest News</h3>
                            <ul>
                                <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">5 Things That Take a Room from Good to Great</a></li>
                                <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">Functional and Stylish Wall-to-Wall Shelves</a></li>
                                <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">9 Unique and Unusual Ways to Display Your TV</a></li>
                                <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">The 5 Secrets to Pulling Off Simple, Minimal Design</a></li>
                                <li><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">How to Make a Huge Impact With Multiples</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h3>Contact Us</h3>
                        <div class="widget widget-address">
                            <address>
                                <span>100 Mainstreet Center, Sydney</span>
                                <span><strong>Phone:</strong>(208) 333 9296</span>
                                <span><strong>Fax:</strong>(208) 333 9298</span>
                                <span><strong>Email:</strong><a href="mailto:contact@archi-interior.com">contact@archi-interior.com</a></span>
                                <span><strong>Web:</strong><a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#">http://archi-interior.com</a></span>
                            </address>
                        </div>
                    </div>
                </div>
            </div>

            <div class="subfooter">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            © Copyright 2017 - Archi Interior Design Template by <span class="id-color">Designesia</span>
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="social-icons">
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-facebook fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-twitter fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-rss fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-google-plus fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-skype fa-lg"></i></a>
                                <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#"><i class="fa fa-dribbble fa-lg"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="http://www.themenesia.com/themeforest/archi-light/index-masonry-med-3-cols.html#" id="back-to-top"></a>
        </footer>
        <!-- footer close -->
    </div>
</div>


<?php echo $this->inlineScript()
    ->prependFile($this->basePath('frontend/js/jquery.themepunch.revolution.min.js'))
    ->prependFile($this->basePath('frontend/js/jquery.themepunch.plugins.min.js'))
    ->prependFile($this->basePath('frontend/js/demo.js'))
    ->prependFile($this->basePath('frontend/js/designesia.js'))
    ->prependFile($this->basePath('frontend/js/enquire.min.js'))
    ->prependFile($this->basePath('frontend/js/jquery.magnific-popup.min.js'))
    ->prependFile($this->basePath('frontend/js/wow.min.js'))
    ->prependFile($this->basePath('frontend/js/validation.js'))
    ->prependFile($this->basePath('frontend/js/video.resize.js'))
    ->prependFile($this->basePath('frontend/js/classie.js'))
    ->prependFile($this->basePath('frontend/js/jquery.countTo.js'))
    ->prependFile($this->basePath('frontend/js/owl.carousel.js'))
    ->prependFile($this->basePath('frontend/js/jquery.scrollto.js'))
    ->prependFile($this->basePath('frontend/js/jquery.flexslider-min.js'))
    ->prependFile($this->basePath('frontend/js/easing.js'))
    ->prependFile($this->basePath('frontend/js/jquery.isotope.min.js'))
    ->prependFile($this->basePath('frontend/js/bootstrap.min.js'))
    ->prependFile($this->basePath('frontend/js/jpreLoader.js'))
    ->prependFile($this->basePath('frontend/js/jquery.min.js'))
; ?>

</body></html>