<!-- subheader -->
<section id="subheader" data-speed="8" data-type="background" style="background-position: 50% -25px; background: url('<?php echo $this->basePath('public/frontend/images/subheader-6.jpg');?>')">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Liên hệ</h1>
                <?php echo $crum;?>
            </div>
        </div>
    </div>
</section>
<!-- subheader close -->

<!-- content begin -->
<div id="content" class="no-bottom">
    <div class="container" id="contact_form">
        <div class="row">

            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-success" role="alert">
                            <p>Cám ơn Bạn đã liên hệ với chúng tôi.<br>
                                Mọi thắc mắc của bạn sẽ được tư vấn trong thời gian sớm nhất.<br> Nhấn vào <a style="text-decoration: underline" href="<?php echo $this->url('home');?>">đây</a> để trở về trang chủ.</p>
                        </div>
                    </div>

                </div>
            </div>

            <div id="sidebar" class="col-md-4">

                <div class="widget widget_text">
                    <h3>Thông tin</h3>
                    <address>
                        <span>562 Nguyễn Chí Thanh, Phường 07, Quận 11, Tp. HCM</span>
                        <span><strong>Phone:</strong>(+84) 22 534 543</span>
                        <span><strong>Fax:</strong>(+84) 22 534 543</span>
                        <span><strong>Email:</strong><a href="mailto:info@lifedeco.vn">info@lifedeco.vn</a></span>
                        <span><strong>Web:</strong><a href="http://lifedeco.vn">lifedeco.vn</a></span>
                    </address>
                </div>
            </div>
        </div>
    </div>
</div>