<?php
$columnName = [
    'ID',
    'Hình',
    'Tên sản phẩm',
    'Danh mục',
    'Lượt xem',
    'Ngày cập nhật',
    'Trạng thái',
];

foreach ($data['data'] as $record) {

    $picture = ($record['product_picture'] == '')
        ? '<img class="img-rounded post-img" src="' . $this->basePath('admin/images/no-picture-person.png') . '" />'
        : '<img class="img-rounded post-img" src="' . $this->serverUrl() . '/thumbs/timthumb.php?src=' . $this->basePath('public/pictures/products/' . $record['product_picture']) .'&w=25px&h=25px">';

    $productCategoryId     = $record['product_category_id'];
    $productCategoryIdStr  = '';

    foreach($productCategoryId as $k => $v) {
        $productCategoryIdStr .= $v['product_category_name'] . ',';
    }

    $columnData[$record['product_id']] = [
        $record['product_id'],
        $picture,
        '<a href="' . $this->url('admin/default', array('controller' => $module, 'action' => 'edit'), array('query' => array('id' => $record['product_id']))) . '">' . ' <strong>' . $this->escapeHtml($record['product_name']) . '</strong>' . '</a>',
        $record['product_category_name'],
        $record['product_view'],
        $this->date()->dateTimeFormat($record['product_date_updated']),
        $data['status'][$record['product_status']],
    ];
}
?>
<?php echo $this->partial('admin/product/search_form', ['data' => $data]); ?>
<table class="table table-striped jambo_table bulk_action">
    <?php echo $this->partial('admin/partial/table_column_name', ['columnName' => $columnName]); ?>
    <?php echo $this->partial('admin/partial/table_column_data', ['columnData' => $columnData, 'module' => $module]); ?>
</table>
